version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #image: digitalocean.com/php
    container_name: iwishco-bot-app
    restart: unless-stopped
    tty: true
    ports:
      - 8500:8000
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: iwishco-bot-mysql
    restart: always
    tty: true
    ports:
      - ${MYSQL_PORT}:3306
    #command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      #MYSQL_ROOT_HOST: '%'
      #
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      #
      #MYSQL_ALLOW_EMPTY_PASSWORD: yes
      #MYSQL_RANDOM_ROOT_PASSWORD: yes
      # 
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - ./mysql/dbdata:/var/lib/mysql/
      #- ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init.sql:/data/application/init.sql
    networks:
      - app-network

  #PhpMyAdmin
  pma:
    image: phpmyadmin:5.1
    container_name: iwishco-bot-phpmyadmin
    environment:
      #- PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
      #- PMA_USER=${MYSQL_USERNAME}
      #- PMA_PASSWORD=${MYSQL_PASSWORD}
      #- PMA_PORT=${MYSQL_PORT}
      - SERVICE_NAME=pma
      - SERVICE_TAGS=dev
    depends_on:
      - db
    ports:
      - 8888:80
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    name: iwishco-bot-app-network
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
